---
- import_tasks: preflight.yml
  tags:
    - always

- import_tasks: uninstall.yml
  become: true
  when: uninstall|bool == true

- import_tasks: install.yml
  become: true
  tags:
    - exploitdog_net_scanner_install
  when: uninstall == false

- import_tasks: configure.yml
  become: true
  tags:
    - exploitdog_net_scanner_configure
  when: uninstall == false

- name: Ensure ExploitDog net scanner systemd service is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: exploitdog_net_scanner
    enabled: true
    state: started
  when: not ansible_check_mode and uninstall == false
  tags:
    - exploitdog_net_scanner_run