---
- name: Assert usage of supported init system
  assert:
    that:
      ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  when: ansible_service_mgr == 'systemd'
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    exploitdog_net_scanner_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"
  when: ansible_service_mgr == 'systemd'
