
- name: Stop exploitdog_net_scanner systemd service
  become: true
  systemd:
    name: exploitdog_net_scanner
    state: stopped
    enabled: no
  when: not ansible_check_mode

- name: Delete service file
  file:
    state: absent
    path: "{{ lookup('vars', '_exploitdog_net_scanner_' + ansible_service_mgr + '_service').file }}"

- name: Delete log
  file:
    state: absent
    path: /var/log/exploitdog_net_scanner

- name: Delete db
  file:
    state: absent
    path: /var/lib/exploitdog_net_scanner

- name: Delete config
  file:
    state: absent
    path: /etc/exploitdog_net_scanner

- name: Delete exploitdog_net_scanner binary
  file:
    state: absent
    path: "{{ _exploitdog_net_scanner_binary_install_dir }}/exploitdog_net_scanner"

# remove if user/group default, not renamed or not root
- name: Create the exploitdog_net_scanner group
  group:
    name: "{{ _exploitdog_net_scanner_system_group }}"
    state: absent
  when: _exploitdog_net_scanner_system_group == "exploitdog-net-scanner"

- name: Create the exploitdog_net_scanner user
  user:
    name: "{{ _exploitdog_net_scanner_system_user }}"
    state: absent
  when: _exploitdog_net_scanner_system_user == "exploitdog-net-scanner"